### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by rafaelcamargo** [glorious-codes/glorious-pitsby#68]
Improve UI to achieve the following goals:

- [x] 1 - Create a **logo** for Pitsby.
- [x] 2 - Create a **favicon** for Pitsby.
- [x] 3 - When we have too many components, we end up with a huge blank space at the right of menu when we scroll it. **So, fit the menu in the viewport height and make it fixed**.
- [x] 4 - Make examples accept styles: https://github.com/glorious-codes/glorious-pitsby/issues/79
- [x] 5 - Move engine menu to sidebar: https://github.com/glorious-codes/glorious-pitsby/issues/77
- [x] 6 - Improve **code indentation**: https://github.com/glorious-codes/glorious-pitsby/issues/63
- [x] 7 - **Limit main width to 1440px** and center it on the remaining space at the right of the sidebar: https://github.com/glorious-codes/glorious-pitsby/pull/82
- [x] 8 - Also when we have too many components, it's not that easy to find one of them. We need to scroll and read several names. **So, make a search input no top of components list** on the menu to search for them instead scroll for them: https://github.com/glorious-codes/glorious-pitsby/pull/82
- [ ] 9 - Make Pitsby **responsive**: https://github.com/glorious-codes/glorious-pitsby/pull/85

**Note:** Before anything, create a mock up for this.

**Comment by rafaelcamargo** [comment]
**1 - Logo**

![logo](https://user-images.githubusercontent.com/4738687/56444172-04832780-62ce-11e9-95e1-1d37c8b4235f.png)

**Comment by rafaelcamargo** [comment]
**2 - Favicon**

![favicon](https://user-images.githubusercontent.com/4738687/56444305-896e4100-62ce-11e9-8e5c-cf4d25c6b0d2.png)

**Comment by rafaelcamargo** [comment]
**Mocukp for 3 and 4**

![mockup](https://user-images.githubusercontent.com/4738687/56451128-90ae4280-6300-11e9-9290-cc679dd014a1.png)

**Comment by rafaelcamargo** [comment]
**Item 3** resolved on https://github.com/glorious-codes/glorious-pitsby/pull/73

**Comment by rafaelcamargo** [comment]
**Mockup for 5**

![mockup](https://user-images.githubusercontent.com/4738687/56546502-10325080-6551-11e9-9c93-6310beee2549.png)

**Comment by rafaelcamargo** [comment]
**Item 6** resolve on #83

**Comment by rafaelcamargo** [comment]
**Mockup for 9**

![mockup-mobile](https://user-images.githubusercontent.com/4738687/57029145-463d9780-6c17-11e9-9b76-b46a6da0b277.png)
